export const MATCHING_PROXIMITY_METERS = 500;
export const DEFAULT_SEARCH_RADIUS_METERS = 1000;
export const OTP_EXPIRATION_SECONDS = 300; // 5 minutes
export const OTP_MAX_ATTEMPTS = 3;
export const GPS_BROADCAST_THROTTLE_MS = 3000; // 3 seconds interval

export const USER_ROLES = {
  RIDER: 'RIDER',
  DRIVER: 'DRIVER',
  ADMIN: 'ADMIN',
} as const;

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
} as const;

export const RIDE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
} as const;

export const RIDE_REQUEST_STATUS = {
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export const TRIP_STATUS = {
  ACCEPTED: 'ACCEPTED',
  OTP_PENDING: 'OTP_PENDING',
  STARTED: 'STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETION_PENDING: 'COMPLETION_PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
